import { College, Accommodation, Course, Inquiry } from "@/types";

export const INITIAL_COURSES: Course[] = [
  {
    id: "course-btech-cse",
    name: "B.Tech Computer Science & Engineering",
    slug: "btech-cse",
    discipline: "Engineering",
    level: "Undergraduate",
    duration: "4 Years",
    collegeCount: 42,
    avgFee: 220000,
  },
  {
    id: "course-btech-ai-ds",
    name: "B.Tech Artificial Intelligence & Data Science",
    slug: "btech-ai-ds",
    discipline: "Engineering",
    level: "Undergraduate",
    duration: "4 Years",
    collegeCount: 36,
    avgFee: 240000,
  },
  {
    id: "course-mbbs",
    name: "MBBS (Bachelor of Medicine & Surgery)",
    slug: "mbbs",
    discipline: "Medical",
    level: "Undergraduate",
    duration: "5.5 Years",
    collegeCount: 14,
    avgFee: 1400000,
  },
  {
    id: "course-bds",
    name: "BDS (Bachelor of Dental Surgery)",
    slug: "bds",
    discipline: "Medical",
    level: "Undergraduate",
    duration: "5 Years",
    collegeCount: 12,
    avgFee: 450000,
  },
  {
    id: "course-bsc-nursing",
    name: "B.Sc Nursing",
    slug: "bsc-nursing",
    discipline: "Medical",
    level: "Undergraduate",
    duration: "4 Years",
    collegeCount: 28,
    avgFee: 120000,
  },
  {
    id: "course-mba",
    name: "MBA (Master of Business Administration)",
    slug: "mba",
    discipline: "Management",
    level: "Postgraduate",
    duration: "2 Years",
    collegeCount: 38,
    avgFee: 320000,
  },
  {
    id: "course-bba",
    name: "BBA (Bachelor of Business Administration)",
    slug: "bba",
    discipline: "Management",
    level: "Undergraduate",
    duration: "3 Years",
    collegeCount: 45,
    avgFee: 110000,
  },
  {
    id: "course-bca",
    name: "BCA (Bachelor of Computer Applications)",
    slug: "bca",
    discipline: "Computer Apps",
    level: "Undergraduate",
    duration: "3 Years",
    collegeCount: 40,
    avgFee: 130000,
  },
  {
    id: "course-mca",
    name: "MCA (Master of Computer Applications)",
    slug: "mca",
    discipline: "Computer Apps",
    level: "Postgraduate",
    duration: "2 Years",
    collegeCount: 22,
    avgFee: 160000,
  },
  {
    id: "course-bcom",
    name: "B.Com (Honours / ACCA Integrated)",
    slug: "bcom",
    discipline: "Arts & Science",
    level: "Undergraduate",
    duration: "3 Years",
    collegeCount: 52,
    avgFee: 95000,
  },
  {
    id: "course-bpt",
    name: "BPT (Bachelor of Physiotherapy)",
    slug: "bpt",
    discipline: "Paramedical & Allied",
    level: "Undergraduate",
    duration: "4.5 Years",
    collegeCount: 16,
    avgFee: 180000,
  }
];

export const INITIAL_COLLEGES: College[] = [
  {
    id: "col-st-aloysius",
    name: "St. Aloysius Institute of Technology & Management",
    slug: "st-aloysius-institute-of-technology",
    location: "Light House Hill, Mangalore",
    city: "Mangalore",
    state: "Karnataka",
    rating: 4.8,
    reviewCount: 1240,
    googleReviewUrl: "https://maps.google.com/?q=St+Aloysius+College+Mangalore",
    startingFee: 150000,
    highestPackage: "₹28.5 LPA",
    averagePackage: "₹7.2 LPA",
    placementRate: 94,
    hasHostel: true,
    bannerImage: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1400&q=80",
    logoImage: "https://lh3.googleusercontent.com/aida-public/AB6AXuD_3wyLfLKm2S3AAzrIBpSd5lr-Hc8tGiuN5qr-WCeJpwaR2G--ylcVM00XKA9lVnylGiDW6DKJc7Y_BNrVArnSkab_f736fOoch69K9XKrzojhz-cVIPLWnDRr5CZ225ikZyTRA5D0SMb4TItHjJrFsv5-sSFPMv6fhbULp3VAJ8QSAqnlpoZd0jmZGa0_CBP42LijML2aaetj1Co8I5wkGnFAr5Havk_z-aCMrc0GhJF2Pgro1L8HCQ",
    about: "St. Aloysius Institute is a premier autonomous educational institution dedicated to academic brilliance, ethical leadership, and industry innovation. Spanning a heritage-rich 50-acre campus right in the heart of Mangalore, the institute boasts state-of-the-art incubation laboratories, multinational research collaborations, and robust placement partnerships.",
    whyChoose: [
      "Ranked Top 50 in India (NIRF 2023) with NAAC A++ accreditation",
      "Over 120+ Fortune 500 recruiting partners offering international placements",
      "Active Student Incubation Cell funded by Karnataka State Innovation Council",
      "Comprehensive on-campus hostels with Wi-Fi, hygienic cafeteria, and gym facilities"
    ],
    establishedYear: 1880,
    accreditation: ["NAAC A++", "UGC Autonomous", "NIRF Top 50", "AICTE Approved"],
    dataSource: "Campus Finder On-Site Verification",
    lastVerifiedAt: "2026-08-25T10:00:00Z",
    isFeatured: true,
    courses: [
      {
        id: "cc-1",
        collegeId: "col-st-aloysius",
        courseName: "B.Tech Computer Science & Engineering",
        discipline: "Engineering",
        duration: "4 Years",
        firstYearFee: 250000,
        annualFee: 250000,
        specializations: ["AI & Machine Learning", "Cloud Computing", "Cyber Security", "Data Science"],
        eligibility: "10+2 with 60% in Physics, Chemistry, Math & KCET/COMEDK/Direct rank",
        seats: 180,
      },
      {
        id: "cc-2",
        collegeId: "col-st-aloysius",
        courseName: "MBA (Master of Business Administration)",
        discipline: "Management",
        duration: "2 Years",
        firstYearFee: 320000,
        annualFee: 320000,
        specializations: ["Finance & Banking", "Business Analytics", "Human Resource", "Marketing"],
        eligibility: "Graduation with minimum 50% + valid MAT/CAT/PGCET score",
        seats: 120,
      },
      {
        id: "cc-3",
        collegeId: "col-st-aloysius",
        courseName: "BCA (Bachelor of Computer Applications)",
        discipline: "Computer Apps",
        duration: "3 Years",
        firstYearFee: 180000,
        annualFee: 180000,
        specializations: ["Full Stack Development", "Cloud & IoT"],
        eligibility: "10+2 in any stream with Mathematics/Statistics/Computer background",
        seats: 150,
      },
      {
        id: "cc-4",
        collegeId: "col-st-aloysius",
        courseName: "B.Com (Professional with ACCA)",
        discipline: "Arts & Science",
        duration: "3 Years",
        firstYearFee: 140000,
        annualFee: 140000,
        specializations: ["ACCA UK Integrated", "FinTech & Analytics"],
        eligibility: "10+2 Commerce/Science with min 55%",
        seats: 200,
      }
    ],
    facilities: [
      { id: "fac-1", name: "High-Speed Wi-Fi Campus", icon: "Wifi", category: "Tech" },
      { id: "fac-2", name: "Smart AC Classrooms", icon: "Monitor", category: "Academics" },
      { id: "fac-3", name: "Modern Central Library", icon: "BookOpen", category: "Academics" },
      { id: "fac-4", name: "Multi-Sport Complex & Ground", icon: "Trophy", category: "Sports" },
      { id: "fac-5", name: "Boys & Girls Separate Hostels", icon: "Home", category: "Living" },
      { id: "fac-6", name: "Medical & Health Care Centre", icon: "HeartPulse", category: "Health" }
    ],
    placements: {
      id: "place-1",
      collegeId: "col-st-aloysius",
      year: 2024,
      placementPercentage: 94,
      averagePackage: "₹7.2 LPA",
      highestPackage: "₹28.5 LPA",
      topRecruiters: ["Microsoft", "Amazon", "Infosys", "TCS", "Accenture", "Deloitte", "KPMG", "Oracle"],
      highlights: [
        "450+ students placed across top tech and financial corporations",
        "18 international offer letters received in UAE and Singapore",
        "Dedicated pre-placement training on DSA, system design, and soft skills"
      ]
    }
  },
  {
    id: "col-nitk",
    name: "National Institute of Technology Karnataka (NITK)",
    slug: "nitk-surathkal",
    location: "Surathkal, Mangalore",
    city: "Surathkal",
    state: "Karnataka",
    rating: 4.9,
    reviewCount: 3820,
    googleReviewUrl: "https://maps.google.com/?q=NITK+Surathkal",
    startingFee: 165000,
    highestPackage: "₹54.0 LPA",
    averagePackage: "₹18.2 LPA",
    placementRate: 98,
    hasHostel: true,
    bannerImage: "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1400&q=80",
    about: "National Institute of Technology Karnataka (NITK), Surathkal, is an Institute of National Importance established by the Government of India. Set across 295 lush acres beside the Arabian Sea, NITK ranks among the topmost engineering institutions in the country, world-renowned for breakthrough research and stellar placements.",
    whyChoose: [
      "Institute of National Importance with NIRF Engineering Rank #12",
      "Private beach access and state-of-the-art supercomputing facilities",
      "Top package of ₹54 LPA with median package exceeding ₹15 LPA",
      "Over 300+ global tech giants hiring directly on campus"
    ],
    establishedYear: 1960,
    accreditation: ["Institute of National Importance", "NIRF Rank 12", "AICTE Approved"],
    dataSource: "Ministry of Education / Verified Institutional Data",
    lastVerifiedAt: "2026-08-28T14:00:00Z",
    isFeatured: true,
    courses: [
      {
        id: "cc-nitk-1",
        collegeId: "col-nitk",
        courseName: "B.Tech Computer Science & Engineering",
        discipline: "Engineering",
        duration: "4 Years",
        firstYearFee: 165000,
        annualFee: 165000,
        specializations: ["Distributed Systems", "Artificial Intelligence", "Security"],
        eligibility: "JEE Main rank through JoSAA/CSAB counselling",
        seats: 120,
      },
      {
        id: "cc-nitk-2",
        collegeId: "col-nitk",
        courseName: "B.Tech Information Technology",
        discipline: "Engineering",
        duration: "4 Years",
        firstYearFee: 165000,
        annualFee: 165000,
        specializations: ["Cloud Architecture", "Data Science"],
        eligibility: "JEE Main rank through JoSAA counselling",
        seats: 110,
      },
      {
        id: "cc-nitk-3",
        collegeId: "col-nitk",
        courseName: "B.Tech Electronics & Communication",
        discipline: "Engineering",
        duration: "4 Years",
        firstYearFee: 165000,
        annualFee: 165000,
        specializations: ["VLSI Design", "Embedded Systems", "Robotics"],
        eligibility: "JEE Main rank through JoSAA counselling",
        seats: 115,
      }
    ],
    facilities: [
      { id: "fac-1", name: "High-Speed Wi-Fi Campus", icon: "Wifi", category: "Tech" },
      { id: "fac-3", name: "Central Digital Library", icon: "BookOpen", category: "Academics" },
      { id: "fac-4", name: "Swimming Pool & Sports Complex", icon: "Trophy", category: "Sports" },
      { id: "fac-5", name: "12 Hostels with Mess", icon: "Home", category: "Living" }
    ],
    placements: {
      id: "place-2",
      collegeId: "col-nitk",
      year: 2024,
      placementPercentage: 98,
      averagePackage: "₹18.2 LPA",
      highestPackage: "₹54.0 LPA",
      topRecruiters: ["Google", "Microsoft", "Apple", "Goldman Sachs", "Uber", "Qualcomm", "Texas Instruments"],
      highlights: [
        "98% overall placement across B.Tech branches",
        "Highest international package of ₹54 LPA",
        "Over 85% of eligible students received pre-placement internship offers"
      ]
    }
  },
  {
    id: "col-yenepoya",
    name: "Yenepoya (Deemed to be University)",
    slug: "yenepoya-deemed-to-be-university",
    location: "Deralakatte, Mangalore",
    city: "Mangalore",
    state: "Karnataka",
    rating: 4.7,
    reviewCount: 950,
    googleReviewUrl: "https://maps.google.com/?q=Yenepoya+University+Deralakatte",
    startingFee: 280000,
    highestPackage: "₹22.0 LPA",
    averagePackage: "₹8.5 LPA",
    placementRate: 91,
    hasHostel: true,
    bannerImage: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1400&q=80",
    about: "Yenepoya University is a premier multidisciplinary healthcare, technology, and allied sciences institution accredited with NAAC Grade 'A+'. With a 1000-bed super-specialty teaching hospital, simulation center, and cutting-edge biotechnology labs, Yenepoya offers comprehensive medical, dental, allied health, and IT programs.",
    whyChoose: [
      "NAAC 'A+' Accredited University with NIRF Top 100 standing",
      "Advanced Advanced Clinical Simulation Centre recognized globally",
      "Multi-specialty 1,000 bed teaching hospital on campus",
      "Global exchange programs with universities in USA, UK, and Europe"
    ],
    establishedYear: 1991,
    accreditation: ["NAAC A+", "UGC Deemed University", "NIRF Top 100", "NMC Approved"],
    dataSource: "Institutional Audit & Official Records",
    lastVerifiedAt: "2026-08-20T12:00:00Z",
    isFeatured: true,
    courses: [
      {
        id: "cc-yene-1",
        collegeId: "col-yenepoya",
        courseName: "MBBS (Bachelor of Medicine & Surgery)",
        discipline: "Medical",
        duration: "5.5 Years",
        firstYearFee: 1800000,
        annualFee: 1800000,
        specializations: ["Clinical Medicine", "Surgery"],
        eligibility: "NEET-UG qualification with 50% in PCB",
        seats: 250,
      },
      {
        id: "cc-yene-2",
        collegeId: "col-yenepoya",
        courseName: "B.Sc Nursing",
        discipline: "Medical",
        duration: "4 Years",
        firstYearFee: 150000,
        annualFee: 150000,
        specializations: ["Critical Care", "Pediatric Nursing"],
        eligibility: "10+2 PCB with 45% minimum",
        seats: 100,
      },
      {
        id: "cc-yene-3",
        collegeId: "col-yenepoya",
        courseName: "BCA (Cloud Computing & Cyber Security)",
        discipline: "Computer Apps",
        duration: "3 Years",
        firstYearFee: 160000,
        annualFee: 160000,
        specializations: ["Cloud Infrastructure", "Information Security"],
        eligibility: "10+2 in any stream",
        seats: 120,
      }
    ],
    facilities: [
      { id: "fac-1", name: "1000-Bed Hospital", icon: "HeartPulse", category: "Health" },
      { id: "fac-2", name: "Advanced Robotics Lab", icon: "Cpu", category: "Tech" },
      { id: "fac-3", name: "Hostels with Mess", icon: "Home", category: "Living" }
    ],
    placements: {
      id: "place-3",
      collegeId: "col-yenepoya",
      year: 2024,
      placementPercentage: 91,
      averagePackage: "₹8.5 LPA",
      highestPackage: "₹22.0 LPA",
      topRecruiters: ["Apollo Hospitals", "Manipal Hospitals", "Fortis", "Wipro Health", "Cognizant"],
      highlights: ["100% internship placement in parent medical hospital"]
    }
  },
  {
    id: "col-sahyadri",
    name: "Sahyadri College of Engineering & Management",
    slug: "sahyadri-college-of-engineering",
    location: "Adyar, Mangalore",
    city: "Mangalore",
    state: "Karnataka",
    rating: 4.6,
    reviewCount: 1100,
    googleReviewUrl: "https://maps.google.com/?q=Sahyadri+College+Mangalore",
    startingFee: 175000,
    highestPackage: "₹40.0 LPA",
    averagePackage: "₹6.8 LPA",
    placementRate: 92,
    hasHostel: true,
    bannerImage: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=1400&q=80",
    about: "Sahyadri College of Engineering & Management, established in 2007 on the banks of Netravati river in Adyar, is celebrated for its project-based learning, startup accelerators, and in-house innovation hubs like Sahyadri Hands-on Learning Lab.",
    whyChoose: [
      "Ranked 'Band Excellent' in ARIIA & NAAC 'A' Accredited",
      "Over 200+ startup projects incubated on-campus",
      "Highest package ₹40 LPA with 200+ visiting companies",
      "Riverside scenic and eco-friendly campus"
    ],
    establishedYear: 2007,
    accreditation: ["NAAC A Grade", "NBA Accredited", "AICTE Approved"],
    dataSource: "Campus Finder Audit",
    lastVerifiedAt: "2026-08-22T09:30:00Z",
    isFeatured: true,
    courses: [
      {
        id: "cc-sah-1",
        collegeId: "col-sahyadri",
        courseName: "B.Tech Computer Science & Engineering",
        discipline: "Engineering",
        duration: "4 Years",
        firstYearFee: 220000,
        annualFee: 220000,
        specializations: ["Data Science", "Cyber Security", "Full Stack Development"],
        eligibility: "10+2 with 45% in PCM + KCET/COMEDK/Direct",
        seats: 240,
      },
      {
        id: "cc-sah-2",
        collegeId: "col-sahyadri",
        courseName: "MBA (Finance / Marketing / HR)",
        discipline: "Management",
        duration: "2 Years",
        firstYearFee: 190000,
        annualFee: 190000,
        specializations: ["FinTech", "Digital Marketing"],
        eligibility: "Graduation with 50% + PGCET/KMAT",
        seats: 120,
      }
    ],
    facilities: [
      { id: "fac-1", name: "In-house Startups & FabLab", icon: "Cpu", category: "Tech" },
      { id: "fac-2", name: "Boys & Girls Hostels", icon: "Home", category: "Living" }
    ],
    placements: {
      id: "place-4",
      collegeId: "col-sahyadri",
      year: 2024,
      placementPercentage: 92,
      averagePackage: "₹6.8 LPA",
      highestPackage: "₹40.0 LPA",
      topRecruiters: ["Adobe", "Cohesity", "SAP Labs", "Capgemini", "LTI Mindtree", "TCS"],
      highlights: ["Record 92% placement rate with average package increase of 15%"]
    }
  },
  {
    id: "col-aj-medical",
    name: "A.J. Institute of Medical Sciences & Research Centre",
    slug: "aj-institute-of-medical-sciences",
    location: "Kuntikana, Mangalore",
    city: "Mangalore",
    state: "Karnataka",
    rating: 4.6,
    reviewCount: 780,
    googleReviewUrl: "https://maps.google.com/?q=AJ+Hospital+Mangalore",
    startingFee: 350000,
    highestPackage: "₹24.0 LPA",
    averagePackage: "₹9.2 LPA",
    placementRate: 95,
    hasHostel: true,
    bannerImage: "https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?auto=format&fit=crop&w=1400&q=80",
    about: "A.J. Institute of Medical Sciences (AJIMS) is a top-tier healthcare education and super-specialty hospital complex in Kuntikana, Mangalore. Known for clinical training, modern ICUs, and comprehensive postgraduate medical residencies.",
    whyChoose: [
      "NMC Approved with state-of-the-art super specialty 900+ bed hospital",
      "Experienced medical faculty and high patient flow for clinical exposure",
      "Modern simulation and pathology laboratory equipment",
      "Direct on-campus hostel facilities for boys and girls"
    ],
    establishedYear: 2002,
    accreditation: ["NMC Approved", "RGUHS Affiliated", "NABH Accredited Hospital"],
    dataSource: "RGUHS Official Portal",
    lastVerifiedAt: "2026-08-15T11:00:00Z",
    isFeatured: false,
    courses: [
      {
        id: "cc-aj-1",
        collegeId: "col-aj-medical",
        courseName: "MBBS",
        discipline: "Medical",
        duration: "5.5 Years",
        firstYearFee: 1600000,
        annualFee: 1600000,
        specializations: ["General Medicine", "Surgery"],
        eligibility: "NEET-UG qualification with PCB 50%",
        seats: 150,
      },
      {
        id: "cc-aj-2",
        collegeId: "col-aj-medical",
        courseName: "B.Sc Medical Laboratory Technology",
        discipline: "Paramedical & Allied",
        duration: "3.5 Years",
        firstYearFee: 110000,
        annualFee: 110000,
        specializations: ["Clinical Pathology", "Biochemistry"],
        eligibility: "10+2 Science with 45%",
        seats: 60,
      }
    ],
    facilities: [
      { id: "fac-1", name: "Super Specialty Hospital", icon: "HeartPulse", category: "Health" },
      { id: "fac-2", name: "Air Conditioned Library", icon: "BookOpen", category: "Academics" }
    ],
    placements: {
      id: "place-5",
      collegeId: "col-aj-medical",
      year: 2024,
      placementPercentage: 95,
      averagePackage: "₹9.2 LPA",
      highestPackage: "₹24.0 LPA",
      topRecruiters: ["AJ Hospital", "Aster DM Healthcare", "Apollo", "KMC"],
      highlights: ["100% paid internship residency guaranteed"]
    }
  },
  {
    id: "col-srinivas",
    name: "Srinivas University & Institute of Technology",
    slug: "srinivas-university-mangalore",
    location: "Mukka & Pandeshwar, Mangalore",
    city: "Mangalore",
    state: "Karnataka",
    rating: 4.5,
    reviewCount: 840,
    googleReviewUrl: "https://maps.google.com/?q=Srinivas+University+Mangalore",
    startingFee: 110000,
    highestPackage: "₹20.0 LPA",
    averagePackage: "₹5.5 LPA",
    placementRate: 88,
    hasHostel: true,
    bannerImage: "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1400&q=80",
    about: "Srinivas University is a private research university established under Karnataka State Act. Offering wide ranges of courses from Allied Health, Physiotherapy, Engineering, Hotel Management to Aviation Studies across multiple campuses in Mangalore.",
    whyChoose: [
      "UGC Recognised Private University with flexible CBCS curriculum",
      "Wide choice of futuristic courses: Cyber Security, Aviation, Physiotherapy",
      "Affordable fee structure with merit scholarship options",
      "Active placement cell with 150+ corporate tie-ups"
    ],
    establishedYear: 1988,
    accreditation: ["UGC Approved", "AICTE Approved", "PCI Approved"],
    dataSource: "Institutional Verified Data",
    lastVerifiedAt: "2026-08-18T16:00:00Z",
    isFeatured: false,
    courses: [
      {
        id: "cc-srini-1",
        collegeId: "col-srinivas",
        courseName: "BCA (Cloud Computing & Cyber Security)",
        discipline: "Computer Apps",
        duration: "3 Years",
        firstYearFee: 120000,
        annualFee: 120000,
        specializations: ["Ethical Hacking", "Cloud Ops"],
        eligibility: "10+2 in any stream",
        seats: 120,
      },
      {
        id: "cc-srini-2",
        collegeId: "col-srinivas",
        courseName: "BPT (Bachelor of Physiotherapy)",
        discipline: "Paramedical & Allied",
        duration: "4.5 Years",
        firstYearFee: 175000,
        annualFee: 175000,
        specializations: ["Sports Rehab", "Neuro Rehab"],
        eligibility: "10+2 PCB 50%",
        seats: 80,
      }
    ],
    facilities: [
      { id: "fac-1", name: "Digital Campus & Labs", icon: "Monitor", category: "Tech" },
      { id: "fac-2", name: "Hostels with Canteen", icon: "Home", category: "Living" }
    ],
    placements: {
      id: "place-6",
      collegeId: "col-srinivas",
      year: 2024,
      placementPercentage: 88,
      averagePackage: "₹5.5 LPA",
      highestPackage: "₹20.0 LPA",
      topRecruiters: ["Wipro", "Infosys", "Apollo", "IndiGo Airlines", "Taj Hotels"],
      highlights: ["Strong industry immersion with mandatory 6-month capstone internship"]
    }
  }
];

export const INITIAL_ACCOMMODATIONS: Accommodation[] = [
  {
    id: "stay-bejai-comfort",
    name: "Royal Palms Luxury Boys Hostel",
    slug: "royal-palms-luxury-boys-hostel-bejai",
    type: "Hostel",
    gender: "Boys",
    area: "Bejai",
    city: "Mangalore",
    monthlyPrice: 6500,
    deposit: 10000,
    rating: 4.8,
    reviewCount: 86,
    mainImage: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=800&q=80"
    ],
    distanceFromColleges: [
      { collegeName: "St. Aloysius College", distance: "1.2 km" },
      { collegeName: "KMC Mangalore", distance: "0.8 km" },
      { collegeName: "AJ Institute of Medical", distance: "2.4 km" }
    ],
    facilities: [
      "High-speed Wi-Fi",
      "Food Included (3 Meals)",
      "Air Conditioning",
      "24/7 CCTV & Security",
      "Hot Water / Geyser",
      "Power Backup"
    ],
    contactPhone: "+91 98451 22334",
    whatsappPhone: "919845122334",
    availableRooms: 4,
    isAvailable: true,
    dataSource: "Physical Property Verification",
    lastVerifiedAt: "2026-08-27T10:00:00Z"
  },
  {
    id: "stay-kadri-serene",
    name: "Serene Garden Girls PG & Residence",
    slug: "serene-garden-girls-pg-kadri",
    type: "PG",
    gender: "Girls",
    area: "Kadri",
    city: "Mangalore",
    monthlyPrice: 5800,
    deposit: 8000,
    rating: 4.9,
    reviewCount: 114,
    mainImage: "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=800&q=80"
    ],
    distanceFromColleges: [
      { collegeName: "St. Aloysius College", distance: "1.8 km" },
      { collegeName: "Canara College", distance: "1.0 km" },
      { collegeName: "Kadri Temple / Bus Stand", distance: "0.3 km" }
    ],
    facilities: [
      "High-speed Wi-Fi",
      "Food Included (3 Meals)",
      "Attached Bathroom",
      "24/7 Female Warden & CCTV",
      "Washing Machine / Laundry",
      "Study Desk & Wardrobe"
    ],
    contactPhone: "+91 94482 77889",
    whatsappPhone: "9448277889",
    availableRooms: 2,
    isAvailable: true,
    dataSource: "Physical Property Verification",
    lastVerifiedAt: "2026-08-29T15:00:00Z"
  },
  {
    id: "stay-deralakatte-medico",
    name: "Medico Haven Luxury PG & Hostel",
    slug: "medico-haven-deralakatte",
    type: "Hostel",
    gender: "Co-ed",
    area: "Deralakatte",
    city: "Mangalore",
    monthlyPrice: 7200,
    deposit: 12000,
    rating: 4.7,
    reviewCount: 92,
    mainImage: "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=800&q=80",
    distanceFromColleges: [
      { collegeName: "Yenepoya University", distance: "0.4 km (5 min walk)" },
      { collegeName: "K.S. Hegde Medical", distance: "0.9 km" },
      { collegeName: "Kanachur Hospital", distance: "2.1 km" }
    ],
    facilities: [
      "High-speed Wi-Fi",
      "Air Conditioning",
      "Food Included (3 Meals)",
      "Attached Bathroom",
      "24/7 Power Backup & Generator",
      "Daily Housekeeping"
    ],
    contactPhone: "+91 97401 88990",
    whatsappPhone: "9740188990",
    availableRooms: 5,
    isAvailable: true,
    dataSource: "Campus Finder Verified Hostels",
    lastVerifiedAt: "2026-08-26T12:00:00Z"
  },
  {
    id: "stay-kottara-studio",
    name: "Urban Nest Student Rooms & Studio",
    slug: "urban-nest-student-rooms-kottara",
    type: "Room",
    gender: "Boys",
    area: "Kottara",
    city: "Mangalore",
    monthlyPrice: 4800,
    deposit: 6000,
    rating: 4.5,
    reviewCount: 48,
    mainImage: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80",
    distanceFromColleges: [
      { collegeName: "AJ Institute of Medical", distance: "1.2 km" },
      { collegeName: "Infosys Kottara", distance: "0.6 km" }
    ],
    facilities: [
      "High-speed Wi-Fi",
      "Attached Bathroom",
      "Kitchenette Facility",
      "24/7 Water Supply",
      "Hot Water / Geyser"
    ],
    contactPhone: "+91 99002 33445",
    whatsappPhone: "9900233445",
    availableRooms: 3,
    isAvailable: true,
    dataSource: "Owner Direct Verified",
    lastVerifiedAt: "2026-08-24T09:00:00Z"
  },
  {
    id: "stay-valencia-girls",
    name: "Grace Villa Premium Girls PG",
    slug: "grace-villa-girls-pg-valencia",
    type: "PG",
    gender: "Girls",
    area: "Valencia",
    city: "Mangalore",
    monthlyPrice: 6200,
    deposit: 9000,
    rating: 4.8,
    reviewCount: 64,
    mainImage: "https://images.unsplash.com/photo-1540518614846-7ede433c4550?auto=format&fit=crop&w=800&q=80",
    distanceFromColleges: [
      { collegeName: "Father Muller Medical College", distance: "0.5 km" },
      { collegeName: "St. Aloysius College", distance: "2.1 km" }
    ],
    facilities: [
      "High-speed Wi-Fi",
      "Food Included (3 Meals)",
      "Air Conditioning",
      "24/7 CCTV & Security",
      "Washing Machine / Laundry"
    ],
    contactPhone: "+91 98450 11223",
    whatsappPhone: "9845011223",
    availableRooms: 3,
    isAvailable: true,
    dataSource: "Physical Property Verification",
    lastVerifiedAt: "2026-08-28T16:00:00Z"
  },
  {
    id: "stay-surathkal-boys",
    name: "Coastal Breeze Boys Hostel",
    slug: "coastal-breeze-boys-hostel-surathkal",
    type: "Hostel",
    gender: "Boys",
    area: "Surathkal",
    city: "Surathkal",
    monthlyPrice: 5500,
    deposit: 7000,
    rating: 4.6,
    reviewCount: 71,
    mainImage: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=800&q=80",
    distanceFromColleges: [
      { collegeName: "NITK Surathkal", distance: "0.7 km" },
      { collegeName: "Surathkal Railway Station", distance: "1.1 km" }
    ],
    facilities: [
      "High-speed Wi-Fi",
      "Food Included (3 Meals)",
      "Hot Water / Geyser",
      "Study Desk & Wardrobe",
      "24/7 Security"
    ],
    contactPhone: "+91 94812 55667",
    whatsappPhone: "9481255667",
    availableRooms: 6,
    isAvailable: true,
    dataSource: "Campus Finder Verified Hostels",
    lastVerifiedAt: "2026-08-25T14:30:00Z"
  }
];

export const INITIAL_INQUIRIES: Inquiry[] = [
  {
    id: "inq-101",
    studentName: "Rahul Sharma",
    whatsappNumber: "+91 98765 12345",
    email: "rahul.sharma@gmail.com",
    collegeName: "St. Aloysius Institute of Technology & Management",
    courseName: "B.Tech Computer Science & Engineering",
    qualification: "12th Science (PCM - 88%)",
    preferredIntake: "2026-2027",
    status: "New",
    counsellorNotes: "Interested in AI/ML specialization. Requested fee discount eligibility.",
    createdAt: "2026-09-01T09:30:00Z",
  },
  {
    id: "inq-102",
    studentName: "Ananya Pai",
    whatsappNumber: "+91 97412 88990",
    email: "ananya.pai@outlook.com",
    collegeName: "Yenepoya (Deemed to be University)",
    courseName: "B.Sc Nursing",
    qualification: "12th Science (PCB - 82%)",
    preferredIntake: "2026-2027",
    status: "Contacted",
    counsellorNotes: "Spoke via WhatsApp. Sent hostel fee breakdown and syllabus.",
    createdAt: "2026-08-31T14:15:00Z",
  },
  {
    id: "inq-103",
    studentName: "Mohammed Zaid",
    whatsappNumber: "+91 98860 33441",
    email: "zaid.m@gmail.com",
    collegeName: "Sahyadri College of Engineering & Management",
    courseName: "MBA (Master of Business Administration)",
    qualification: "B.Com (68%)",
    preferredIntake: "2026-2027",
    status: "Interested",
    counsellorNotes: "Scheduled campus visit for next Saturday.",
    createdAt: "2026-08-30T11:45:00Z",
  },
  {
    id: "inq-104",
    studentName: "Sneha Hegde",
    whatsappNumber: "+91 94811 77665",
    email: "sneha.hegde@gmail.com",
    collegeName: "NITK Surathkal",
    courseName: "B.Tech Computer Science & Engineering",
    qualification: "12th Science (JEE Main 99.2 percentile)",
    preferredIntake: "2026-2027",
    status: "Converted",
    counsellorNotes: "Secured JoSAA seat. Admission confirmed.",
    createdAt: "2026-08-28T16:20:00Z",
  }
];
